version: '3'
services:
  nginx:
    image:
    ports:
      - 8088:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.php:/var/www/html/
    depends_on:
      - php

  php:
    image: php:latest
    volumes:
      - ./index.php:/var/www/html/index.php
